package com.rakib.model;
// Generated Nov 15, 2017 3:52:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private String name;
     private boolean admin;
     private Set<Userrole> userroles = new HashSet<Userrole>(0);

    public Role() {
    }

	
    public Role(String name, boolean admin) {
        this.name = name;
        this.admin = admin;
    }
    public Role(Project project, String name, boolean admin, Set<Userrole> userroles) {
       this.project = project;
       this.name = name;
       this.admin = admin;
       this.userroles = userroles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public Set<Userrole> getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Set<Userrole> userroles) {
        this.userroles = userroles;
    }




}


